### ISSUE TITLE
Draggable - UX suggestion

### ISSUE THREAD

**Issue by jakobhoeg** [JaleelB/shadcn-tag-input#11]
Hey! 
First off, great contribution to OSS.

I have a minor feature that could be cool to implement for the draggable tags. 
When dragging between each tag, it would increase the UX if there was some sort of visual cue (other than the dragging icon), indicating that they can be dragged.

An idea I have in mind is that when you drag a tag over another, the stationary tag moves out of the way, indicating that the dragged tag can be dropped. Maybe also add a slight bg-color to further visualize that it can be dropped there.

Example of the tag moving out of the way:
https://react-beautiful-dnd.netlify.app/iframe.html?id=board--simple

Kind regards

**Comment by JaleelB** [comment]
Hey @jakobhoeg,

Apologies for the delay – work got a bit hectic on my end. However, I'm excited to share that the feature you suggested for the draggable tags has now been implemented! 🎉

I've incorporated visual cues that indicate where you can drop the tags, along with a subtle background color change to enhance the drag-and-drop experience. This should make the UI more intuitive, similar to the example you provided.

Please give it a try and let me know your thoughts. Your feedback is incredibly valuable, and I appreciate your patience and contribution to improving the project.
