### ISSUE TITLE
Tag Shapes Property - Rounded vs Pill

### ISSUE THREAD

**Issue by aryanprince** [JaleelB/shadcn-tag-input#3]
## Summary
Hey, just wanted to point out that the pill shape buttons and rounded shape buttons in the UI components seem to be swapped. I could be totally wrong, but I thought I'd ask if that's what you intended. I'd like to make a PR for this if this was unintentional :)

## Possible solution

In the `shape` property for the [`tag-input.tsx`](https://github.com/JaleelB/shadcn-tag-input/blob/240d96bc18d9292a19da1bfed103a13d5f1667a4/components/tag-input.tsx#L35) component, `rounded` could be `rounded-lg` and `pill` could be `rounded-full`, like the image I found online on the right:

![image](https://github.com/JaleelB/shadcn-tag-input/assets/45622345/424b6832-b61b-4515-8855-5e07ee0c28ec) ![image](https://github.com/JaleelB/shadcn-tag-input/assets/45622345/f62f85d4-7f7a-44ed-8e2c-a26b11df931c)

## Current screenshots from [demo website:](https://shadcn-tag-input.vercel.app/)

Rounded (for shadcn-tag-input):

![image](https://github.com/JaleelB/shadcn-tag-input/assets/45622345/283fe65d-51dc-4b03-b11d-58b22a59d16c)

Pill (for shadcn-tag-input):

![image](https://github.com/JaleelB/shadcn-tag-input/assets/45622345/91dbef13-3f08-432e-9197-1c8209f546ea)

**Comment by JaleelB** [comment]
Hey, this was unintentional. Thanks for pointing that out. Create the PR, and I'll approve it right away
