### ISSUE TITLE
Is it possible to link autocomplete with the addition of new tags?

### ISSUE THREAD

**Issue by jacquesuhlemann** [JaleelB/shadcn-tag-input#5]
It looks like autocomplete is preventing the addition of new tags. Is it possible to combine this so that autocomplete remains functional but you can also add new tags with comma or enter?

**Comment by JaleelB** [comment]
Thank you for bringing up this issue. II've successfully addressed the problem you encountered with the autocomplete functionality interfering with the addition of new tags.

The changes have been committed and merged into the main branch. Please feel free to pull the latest version and give it a try. 

https://github.com/JaleelB/shadcn-tag-input/assets/78449846/f713fd5b-b5af-47b5-bee8-dfe72cd8039f

**Comment by yuri2peter** [comment]
This bug comes back in version 1.4.6
